version = 1

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["angular"]

[[analyzers]]
name = "csharp"
enabled = true

[[transformers]]
name = "dotnet-format"
enabled = true